---
# Per environment values which override defaults in hmpps-jobs-board-reporting-ui/values.yaml

generic-service:
  ingress:
    host: jobs-board-reporting.hmpps.service.justice.gov.uk

  env:
    ENVIRONMENT: prod
    S3_REGION: eu-west-2
    INGRESS_URL: "https://jobs-board-reporting.hmpps.service.justice.gov.uk"
    DPS_URL: "https://digital.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api.hmpps.service.justice.gov.uk"
    NOMIS_USER_ROLES_API_URL: "https://nomis-user-roles-api.prison.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    AUDIT_ENABLED: "false"
    JOB_API_URL: "https://jobs-board-api.hmpps.service.justice.gov.uk"
    PRISONER_SEARCH_URL: "https://prisoner-search.prison.service.justice.gov.uk"
    ESWE_PROFILE_API_URL: "https://education-employment-api.hmpps.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components.hmpps.service.justice.gov.uk"
    WORK_AFTER_RELEASE_URL: "https://get-ready-for-work.hmpps.service.justice.gov.uk"
    SYSTEM_PHASE: PROD

generic-prometheus-alerts:
  alertSeverity: education-alerts
